/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Database.beans.Employee;
import Database.tables.AccountManager;
import Database.tables.EmployeeManager;
import Users.UserAccount;
import Utility.Helper;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sachintha
 */
public class AccountRegistration extends javax.swing.JPanel {

    private UserAccount currentAccount;
    private Employee employee = null;

    /**
     * Creates new form AccountRegistration
     */
    public AccountRegistration() {
        initComponents();
        disableFields();
        tf_nic.grabFocus();
    }

    private void disableFields() {
        tf_fn.setEditable(false);
        tf_ln.setEditable(false);
        tf_mobile.setEditable(false);
        tf_role.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cb_active = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_nic = new javax.swing.JTextField();
        tf_mobile = new javax.swing.JTextField();
        tf_role = new javax.swing.JTextField();
        tf_ln = new javax.swing.JTextField();
        tf_fn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cb_report = new javax.swing.JCheckBox();
        cb_grn = new javax.swing.JCheckBox();
        cb_registration = new javax.swing.JCheckBox();
        cb_reservation = new javax.swing.JCheckBox();
        cb_menu = new javax.swing.JCheckBox();
        cb_invoice = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(55, 63, 75));
        setMaximumSize(new java.awt.Dimension(1366, 580));
        setMinimumSize(new java.awt.Dimension(1366, 580));
        setPreferredSize(new java.awt.Dimension(1366, 580));

        jPanel1.setBackground(new java.awt.Color(55, 63, 75));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 580));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 580));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee", "NIC", "User Account", "User Name", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 1033, 276));

        cb_active.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_active.setForeground(new java.awt.Color(255, 255, 255));
        cb_active.setText("Active");
        cb_active.setOpaque(false);
        jPanel1.add(cb_active, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 50, 100, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Role");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIC");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, -1, -1));

        tf_nic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_nicKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_nicKeyTyped(evt);
            }
        });
        jPanel1.add(tf_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 90, 20));

        tf_mobile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(tf_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 90, 20));

        tf_role.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(tf_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 90, 20));

        tf_ln.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(tf_ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 110, 20));

        tf_fn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(tf_fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 110, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Find All Accounts");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 150, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Update Account");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 150, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Create New Account");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 180, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 150, 30));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 150, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Privilages"));
        jPanel2.setOpaque(false);

        cb_report.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_report.setForeground(new java.awt.Color(255, 255, 255));
        cb_report.setText("Report");
        cb_report.setOpaque(false);

        cb_grn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_grn.setForeground(new java.awt.Color(255, 255, 255));
        cb_grn.setText("GRN");
        cb_grn.setOpaque(false);

        cb_registration.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_registration.setForeground(new java.awt.Color(255, 255, 255));
        cb_registration.setText("Registration");
        cb_registration.setOpaque(false);

        cb_reservation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_reservation.setForeground(new java.awt.Color(255, 255, 255));
        cb_reservation.setText("Reservation");
        cb_reservation.setOpaque(false);

        cb_menu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_menu.setForeground(new java.awt.Color(255, 255, 255));
        cb_menu.setText("Menu");
        cb_menu.setOpaque(false);

        cb_invoice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_invoice.setForeground(new java.awt.Color(255, 255, 255));
        cb_invoice.setText("Invoice");
        cb_invoice.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_grn)
                    .addComponent(cb_menu))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_registration)
                    .addComponent(cb_reservation))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_invoice)
                    .addComponent(cb_report))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cb_grn)
                        .addGap(15, 15, 15)
                        .addComponent(cb_menu))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cb_registration)
                        .addGap(15, 15, 15)
                        .addComponent(cb_reservation))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cb_invoice)
                        .addGap(15, 15, 15)
                        .addComponent(cb_report)))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 80, 320, 100));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Re type Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mobile");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, -1, -1));

        tf_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 120, 20));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 120, -1));
        jPanel1.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        clearFields();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        addAcountsByUser();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        addNewAccount();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        updateAccount();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loadAllAccounts();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_nicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nicKeyTyped

    }//GEN-LAST:event_tf_nicKeyTyped

    private void tf_nicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nicKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addAcountsByUser();
        }
    }//GEN-LAST:event_tf_nicKeyPressed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addSelectedAccountToFields();
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            addSelectedAccountToFields();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void updateAccount() {
        if (this.currentAccount == null) {
            JOptionPane.showMessageDialog(this, "Please find and select an a ccount first!", "No account selected!", JOptionPane.QUESTION_MESSAGE);
            tf_nic.grabFocus();
            tf_nic.setEditable(true);
            return;
        }
        currentAccount.setGrn(cb_grn.isSelected());
        currentAccount.setInvoice(cb_invoice.isSelected());
        currentAccount.setMenu(cb_menu.isSelected());
        currentAccount.setPassword(jPasswordField1.getText());
        currentAccount.setRegistration(cb_registration.isSelected());
        currentAccount.setReport(cb_report.isSelected());
        currentAccount.setReservation(cb_reservation.isSelected());
        currentAccount.setStatus(cb_active.isSelected());
        currentAccount.setUserName(tf_username.getText());

        boolean flag = false;

        String psw = jPasswordField1.getText();
        String ps = jPasswordField2.getText();
        if (!psw.isEmpty() || !ps.isEmpty()) {
            if (!ps.equals(psw)) {
                JOptionPane.showMessageDialog(this, "Passwords don't match!. Please retype the passwords.", "Invalid passwords!", JOptionPane.QUESTION_MESSAGE);
                jPasswordField1.grabFocus();
                jPasswordField1.selectAll();
                return;
            } else {
                if (JOptionPane.showConfirmDialog(this, "Confirm update?", "Confirm!", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    flag = AccountManager.updateRow(currentAccount, true);
                } else {
                    return;
                }
            }
        } else {
            if (JOptionPane.showConfirmDialog(this, "Confirm update?", "Confirm!", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                flag = AccountManager.updateRow(currentAccount, false);
            } else {
                return;
            }
        }
        if (flag) {
            JOptionPane.showMessageDialog(this, "Account created successfully!", "Success !", JOptionPane.INFORMATION_MESSAGE);
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Accout creation failed!", "Error !", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void addSelectedAccountToFields() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }
        int acid = Integer.parseInt(jTable1.getValueAt(selectedRow, 2).toString());
        UserAccount ac = AccountManager.getRow(acid);
        Employee emp = AccountManager.getEmployeeOfAccount(acid);

        tf_nic.setText(emp.getNic());
        tf_nic.setEditable(false);
        tf_fn.setText(emp.getFname());
        tf_ln.setText(emp.getLname());
        tf_mobile.setText(emp.getTp());
        tf_role.setText(emp.getRole());
        tf_username.setText(ac.getUserName());
        tf_username.setEditable(false);
        cb_active.setSelected(ac.isStatus());
        cb_grn.setSelected(ac.isGrn());
        cb_invoice.setSelected(ac.isInvoice());
        cb_menu.setSelected(ac.isMenu());
        cb_registration.setSelected(ac.isRegistration());
        cb_report.setSelected(ac.isReport());
        cb_reservation.setSelected(ac.isReservation());
        this.currentAccount = ac;
    }

    private void addNewAccount() {
        if (!validateFields()) {
            return;
        }
        UserAccount a = new UserAccount();
        a.setEmpId(EmployeeManager.getIdByNic(tf_nic.getText()));
        a.setGrn(cb_grn.isSelected());
        a.setInvoice(cb_invoice.isSelected());
        a.setMenu(cb_menu.isSelected());
        a.setPassword(jPasswordField1.getText());
        a.setRegistration(cb_registration.isSelected());
        a.setReport(cb_report.isSelected());
        a.setReservation(cb_reservation.isSelected());
        a.setStatus(cb_active.isSelected());
        a.setUserName(tf_username.getText());
        if (AccountManager.addRow(a)) {
            JOptionPane.showMessageDialog(this, "Account created successfully!", "Success !", JOptionPane.INFORMATION_MESSAGE);
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Accout creation failed!", "Error !", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void clearFields() {
        tf_nic.setText(null);
        tf_nic.setEditable(true);

        tf_ln.setText(null);
        tf_fn.setText(null);
        tf_mobile.setText(null);
        tf_role.setText(null);

        tf_username.setText(null);
        tf_username.setEditable(true);

        jPasswordField1.setText(null);
        jPasswordField2.setText(null);
        cb_active.setSelected(false);
        cb_grn.setSelected(false);
        cb_invoice.setSelected(false);
        cb_menu.setSelected(false);
        cb_registration.setSelected(false);
        cb_report.setSelected(false);
        cb_reservation.setSelected(false);
        ((DefaultTableModel) jTable1.getModel()).setRowCount(0);
        this.currentAccount = null;
        tf_nic.grabFocus();
    }

    private boolean validateFields() {
        if (this.employee == null) {
            JOptionPane.showMessageDialog(this, "Please select an employee first.", "No employee selected!", JOptionPane.QUESTION_MESSAGE);
            tf_nic.grabFocus();
            tf_nic.selectAll();
            return false;
        }
        if (tf_username.getText().isEmpty()) {
            tf_username.grabFocus();
            return false;
        }
        String p1 = jPasswordField1.getText();
        String p2 = jPasswordField2.getText();
        if (p1.isEmpty()) {
            jPasswordField1.grabFocus();
            return false;
        }
        if (p2.isEmpty()) {
            jPasswordField2.grabFocus();
            return false;
        }
        if (!p1.equals(p2)) {
            JOptionPane.showMessageDialog(this, "Passwords don't match!. Please retype the passwords.", "Invalid passwords!", JOptionPane.QUESTION_MESSAGE);
            jPasswordField1.grabFocus();
            jPasswordField1.selectAll();
            return false;
        }
        return true;
    }

    private void loadAllAccounts() {
        ArrayList<UserAccount> all = AccountManager.getAll();
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        clearFields();
        for (UserAccount a : all) {
            if (a == null) {
                continue;
            }
            Vector v = new Vector();
            Employee e = EmployeeManager.getRow(a.getEmpId());
            v.add(e.getId());
            v.add(e.getNic());
            v.add(a.getId());
            v.add(a.getUserName());
            v.add(a.isStatus() ? "Active" : "Disabled");
            dtm.addRow(v);
        }
    }

    private void addAcountsByUser() {
        String nic = tf_nic.getText();
        if (!Helper.validateNic(nic)) {
            JOptionPane.showMessageDialog(this, "Please enter valid nic!", "Invalid nic", JOptionPane.QUESTION_MESSAGE);
            tf_nic.grabFocus();
            tf_nic.selectAll();
            return;
        }
        int id = EmployeeManager.getIdByNic(nic);
        if (id == -1) {
            JOptionPane.showMessageDialog(this, "No employee found!", null, JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);

        Employee e = EmployeeManager.getRow(id);
        this.employee = e;
        tf_fn.setText(e.getFname());
        tf_ln.setText(e.getLname());
        tf_mobile.setText(e.getTp());
        tf_role.setText(e.getRole());
        tf_nic.setEditable(false);

        ArrayList<Integer> acs = AccountManager.getAccounts(id);
        for (Integer i : acs) {
            UserAccount row = AccountManager.getRow(i);
            Vector v = new Vector();
            v.add(id);
            v.add(nic);
            v.add(i);
            v.add(row.getUserName());
            v.add(row.isStatus() ? "Active" : "Disabled");
            dtm.addRow(v);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb_active;
    private javax.swing.JCheckBox cb_grn;
    private javax.swing.JCheckBox cb_invoice;
    private javax.swing.JCheckBox cb_menu;
    private javax.swing.JCheckBox cb_registration;
    private javax.swing.JCheckBox cb_report;
    private javax.swing.JCheckBox cb_reservation;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tf_fn;
    private javax.swing.JTextField tf_ln;
    private javax.swing.JTextField tf_mobile;
    private javax.swing.JTextField tf_nic;
    private javax.swing.JTextField tf_role;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
