package GUI;

import Database.DB;
import Database.beans.MenuItem;
import Database.tables.MenuItemManager;
import Database.tables.MenuManager;
import Utility.Helper;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sahan maduka
 */
public class ManageMenu extends javax.swing.JPanel {

    /**
     * Creates new form View_menu
     */
    public ManageMenu() {
        initComponents();
        fillMenus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbox_menu = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_items_all = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(55, 63, 75));
        setMaximumSize(new java.awt.Dimension(1366, 580));
        setMinimumSize(new java.awt.Dimension(1366, 580));
        setPreferredSize(new java.awt.Dimension(1366, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbox_menu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbox_menuItemStateChanged(evt);
            }
        });
        cbox_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_menuActionPerformed(evt);
            }
        });
        add(cbox_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 224, 33));

        tbl_items_all.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Code", "Item Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_items_all);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 570, 480));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADDITIONAL ITEM");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, -1, -1));

        jButton1.setText("<< ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 73, -1));

        jButton2.setText("REMOVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TOTAL");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, -1, -1));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 130, 30));

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 121, 43));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Code", "Status", "Item Name", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 590, 480));

        jButton5.setText("All Menu Items");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 20, 180, 30));

        jButton6.setText("Clear ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 130, -1));

        jButton4.setText("Calculate");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 90, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void cbox_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_menuActionPerformed

        addItemsBySelectedName();
    }//GEN-LAST:event_cbox_menuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int selectedRow = tbl_items_all.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }
        DefaultTableModel t = (DefaultTableModel) jTable2.getModel();

        MenuItem i = MenuItemManager.getRowById(Integer.parseInt(tbl_items_all.getValueAt(selectedRow, 0).toString()), true);
        if (i == null) {
            return;
        }
        if (doesIdExistInList(String.valueOf(i.getId()))) {
            JOptionPane.showMessageDialog(this, "This item already exists!");
            return;
        }
        Vector v = new Vector();
        v.add(i.getId());
        v.add(i.getCode());
        v.add(i.isStatus());
        v.add(i.getName());
        v.add(i.getPrice().setScale(2).toBigInteger());
        t.addRow(v);
        t = (DefaultTableModel) tbl_items_all.getModel();
        t.removeRow(selectedRow);
    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean doesIdExistInList(String id) {
        int rowCount = jTable2.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            if (jTable2.getValueAt(i, 0).toString().equals(id)) {
                return true;
            }
        }
        return false;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        int i = jTable2.getSelectedRow();
        if (i != -1) {
            dtm.removeRow(i);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    int sum = 0;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        loadAllItems();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void loadAllItems() {
        try (
                ResultSet all = MenuItemManager.getAll(true);) {
            DefaultTableModel dtm = (DefaultTableModel) tbl_items_all.getModel();
            dtm.setRowCount(0);
            while (all.next()) {
                Vector v = new Vector();
                v.add(all.getString("idmenu_item"));
                v.add(all.getString("code"));
                v.add(all.getString("itemname"));
                v.add(all.getString("price"));
                dtm.addRow(v);
            }

        } catch (Exception e) {
            DB.processException(e);
        }
    }
    private void cbox_menuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbox_menuItemStateChanged
        // TODO add your handling code here:
        addItemsBySelectedName();
    }//GEN-LAST:event_cbox_menuItemStateChanged

    private void addItemsBySelectedName() {
        String name = cbox_menu.getSelectedItem().toString();
        if (name.isEmpty()) {
            return;
        }
        String sql = "select *,mi.code as code,mi.itemname as name from menu m inner join menu_has_item mhi inner join"
                + " menu_item mi on m.idmenu = mhi.menu_idmenu and mhi.menu_item_idmenu_item = mi.idmenu_item "
                + " where m.menuname = '" + name + "' order by mi.code, mi.itemname";
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        dtm.setRowCount(0);
        try (
                ResultSet rs = DB.search(sql);) {
            if (rs == null) {
                return;
            }
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("idmenu_item"));
                v.add(rs.getString("code"));
                v.add(rs.getBoolean("mi.status"));
                v.add(rs.getString("name"));
                v.add(rs.getString("mi.price"));
                jTextField1.setText(rs.getString("m.price"));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            DB.processException(e);
        }
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jTable2.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Please select items of the menu.", "No item selected!", JOptionPane.QUESTION_MESSAGE);
        } else if (jTextField1.getText().isEmpty()) {
            jTextField1.grabFocus();
        } else {
            updateMenu();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void updateMenu() {
        int icount = jTable2.getRowCount();
        int mId = MenuManager.getIdByName(cbox_menu.getSelectedItem().toString());
        if (mId == -1) {
            return;
        }
        if (DB.iud("delete from menu_has_item where menu_idmenu='" + mId + "'")) {
            boolean flag = true;
            String sql = "";
            for (int i = 0; i < icount; i++) {
                String miid = jTable2.getValueAt(i, 0).toString();
                sql = "insert into menu_has_item(menu_item_idmenu_item,menu_idmenu) values('" + miid + "','" + mId + "' )";
                flag = DB.iud(sql);
            }
            flag = DB.iud("update menu set price = '" + jTextField1.getText() + "' where idmenu='" + mId + "' limit 1");
            if (flag) {
                JOptionPane.showMessageDialog(this, "Updated successfully.", "Success!", JOptionPane.INFORMATION_MESSAGE);
                clearFields();
            }

        }

    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        clearFields();
    }//GEN-LAST:event_jButton6ActionPerformed

    public void clearFields() {
        ((DefaultTableModel) tbl_items_all.getModel()).setRowCount(0);
        ((DefaultTableModel) jTable2.getModel()).setRowCount(0);
        jTextField1.setText(null);

        fillMenus();
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int rowCount = jTable2.getRowCount();
        BigDecimal total = BigDecimal.ZERO;
        for (int i = 0; i < rowCount; i++) {
            total = total.add(new BigDecimal(jTable2.getValueAt(i, 4).toString()));
        }
        jTextField1.setText(total.setScale(2).toString());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        Helper.numericDataAdd(jTextField1, evt);
    }//GEN-LAST:event_jTextField1KeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbox_menu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbl_items_all;
    // End of variables declaration//GEN-END:variables

    public void fillMenus() {
        try {
            ResultSet rs = DB.search("SELECT * from menu");
            DefaultComboBoxModel dcm = new DefaultComboBoxModel();
            while (rs.next()) {
                String name = rs.getString("menuname");
                dcm.addElement(name);
            }
            cbox_menu.setModel(dcm);
        } catch (Exception e) {
            DB.processException(e);
        }
    }

}
