package GUI;

import Database.DB;
import Database.tables.LoginManager;
import Database.tables.ProductManager;
import Database.tables.ReservationManager;
import GUI.Frames;
import Utility.Helper;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.util.Date;
import java.util.Vector;
import static javax.swing.JFrame.setDefaultLookAndFeelDecorated;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import org.jvnet.substance.skin.SubstanceBusinessBlueSteelLookAndFeel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sahan maduka
 */
public class Stock extends javax.swing.JFrame {

    /**
     * Creates new form S_Search_P_Search
     */
    public Stock() {
        initComponents();
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent evt) {
                LoginManager.logOut();
                Frames.showLoginWindow();
            }
        });
        ActionListener updateClockAction = new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                jLabel3.setText(Helper.getDateTimeForDb(new Date()));
            }

        };
        Timer t = new Timer(1000, updateClockAction);

        t.start();
    }

    /*
    implement logic for clearing all sub forms
     */
    public void clearFields() {
        ((DefaultTableModel) tbl_stock.getModel()).setRowCount(0);
        ((DefaultTableModel) tbl_product.getModel()).setRowCount(0);
        tf_id_product.setText(null);
        tf_id_stock.setText(null);
        tf_name_product.setText(null);
        tf_name_stock.setText(null);
        tf_id_stock.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lb_user = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_stock = new javax.swing.JTable();
        tf_id_stock = new javax.swing.JTextField();
        tf_name_stock = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tf_id_product = new javax.swing.JTextField();
        tf_name_product = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_product = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 204, 153));
        jPanel4.setMaximumSize(new java.awt.Dimension(1076, 152));
        jPanel4.setMinimumSize(new java.awt.Dimension(1076, 152));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("TIME");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setText("Stock");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 36, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("1996/10/14");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 11, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("LOG USER");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 58, -1, -1));

        lb_user.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_user.setText("Name");
        jPanel4.add(lb_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 58, -1, -1));

        jButton14.setText("HOME");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 40, 116, 45));

        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 580));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 580));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(55, 63, 75));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(55, 63, 75));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STOCK", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel3.setMaximumSize(new java.awt.Dimension(484, 441));
        jPanel3.setMinimumSize(new java.awt.Dimension(484, 441));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Name");

        tbl_stock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Code", "Name", "Qty", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_stock);

        tf_id_stock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_id_stockKeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_id_stock, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(tf_name_stock))
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(44, 44, 44)
                        .addComponent(jButton5)))
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_id_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_name_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 650, 680));

        jPanel5.setBackground(new java.awt.Color(55, 63, 75));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRODUCT", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel5.setMaximumSize(new java.awt.Dimension(484, 441));
        jPanel5.setMinimumSize(new java.awt.Dimension(484, 441));
        jPanel5.setPreferredSize(new java.awt.Dimension(484, 441));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Code");

        tf_id_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_id_productActionPerformed(evt);
            }
        });
        tf_id_product.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_id_productKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Name");

        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tbl_product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "GRN", "Qty", "Exp", "Buying Price", "Selling Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_product);

        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_id_product, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(tf_name_product))
                .addGap(67, 67, 67)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(56, 56, 56)
                        .addComponent(jButton6)))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_id_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_name_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 31, 640, 680));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 840));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        Frames.showMain();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loadByStockId();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        loadByStockName();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tf_id_stockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_id_stockKeyTyped
        Helper.codeIdd(tf_id_stock, evt, 6);
    }//GEN-LAST:event_tf_id_stockKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        clearFields();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        loadByProductCode();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tf_id_productKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_id_productKeyTyped
        Helper.codeIdd(tf_id_product, evt, 5);
    }//GEN-LAST:event_tf_id_productKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        loadByProductName();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        clearFields();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tf_id_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_id_productActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_id_productActionPerformed

    private void loadByProductCode() {
        String text = tf_id_product.getText();
        if (text.isEmpty()) {
            tf_id_product.grabFocus();
            return;
        }
        String sql = "select type,idproduct from product where code ='" + text + "' limit 1";
        String type = null;
        String id = null;
        try (
                ResultSet search = DB.search(sql);) {
            if (search.next()) {
                type = search.getString("type");
                id = search.getString("idproduct");
            }
        } catch (Exception e) {
            DB.processException(e);
        }
        if (type == null) {
            return;
        }

        DefaultTableModel dtm = (DefaultTableModel) tbl_product.getModel();
        if (type.equals("sell")) {
            sql = "select * from sell_item where product_idproduct = '" + id + "'";
            try (
                    ResultSet rs = DB.search(sql);) {
                dtm.setRowCount(0);
                while (rs.next()) {
                    Vector v = new Vector();
                    v.add(rs.getString("idsell_item"));
                    v.add(rs.getString("grn_idgrn"));
                    v.add(rs.getString("qty"));
                    v.add(Helper.getDateForDb(rs.getDate("exp")));
                    v.add(rs.getString("buyingprice"));
                    v.add(rs.getString("unitprice"));
                    dtm.addRow(v);
                }
            } catch (Exception e) {
                DB.processException(e);
            }
        } else {
            sql = "select * from raw_item where product_idproduct = '" + id + "'";
            try (
                    ResultSet rs = DB.search(sql);) {
                dtm.setRowCount(0);
                while (rs.next()) {
                    Vector v = new Vector();
                    v.add(rs.getString("idraw_item"));
                    v.add(rs.getString("grn_idgrn"));
                    v.add(rs.getString("qty"));
                    v.add(Helper.getDateForDb(rs.getDate("exp")));
                    v.add(rs.getString("buying_price"));
                    v.add("N/A");
                    dtm.addRow(v);
                }
            } catch (Exception e) {
                DB.processException(e);
            }
        }

    }

    private void loadByProductName() {
        String text = tf_name_product.getText();
        if (text.isEmpty()) {
            tf_name_product.grabFocus();
            return;
        }
        String sql = "select type,idproduct from product where name ='" + text + "' limit 1";
        String type = null;
        String id = null;
        try (
                ResultSet search = DB.search(sql);) {
            if (search.next()) {
                type = search.getString("type");
                id = search.getString("idproduct");
            }
        } catch (Exception e) {
            DB.processException(e);
        }
        if (type == null) {
            return;
        }

        DefaultTableModel dtm = (DefaultTableModel) tbl_product.getModel();
        if (type.equals("sell")) {
            sql = "select * from sell_item where product_idproduct = '" + id + "'";
            try (
                    ResultSet rs = DB.search(sql);) {
                dtm.setRowCount(0);
                while (rs.next()) {
                    Vector v = new Vector();
                    v.add(rs.getString("idsell_item"));
                    v.add(rs.getString("grn_idgrn"));
                    v.add(rs.getString("qty"));
                    v.add(Helper.getDateForDb(rs.getDate("exp")));
                    v.add(rs.getString("buyingprice"));
                    v.add(rs.getString("unitprice"));
                    dtm.addRow(v);
                }
            } catch (Exception e) {
                DB.processException(e);
            }
        } else {
            sql = "select * from raw_item where product_idproduct = '" + id + "'";
            try (
                    ResultSet rs = DB.search(sql);) {
                dtm.setRowCount(0);
                while (rs.next()) {
                    Vector v = new Vector();
                    v.add(rs.getString("idraw_item"));
                    v.add(rs.getString("grn_idgrn"));
                    v.add(rs.getString("qty"));
                    v.add(Helper.getDateForDb(rs.getDate("exp")));
                    v.add(rs.getString("buying_price"));
                    v.add("N/A");
                    dtm.addRow(v);
                }
            } catch (Exception e) {
                DB.processException(e);
            }
        }

    }

    private void loadByStockId() {
        String id = tf_id_stock.getText();
        if (id.isEmpty()) {
            tf_id_stock.grabFocus();
            return;
        }

        String sql = "select *, (select coalesce(sum(qty),0) from sell_item where product_idproduct = p.idproduct) + "
                + "(select coalesce(sum(qty),0)  from raw_item where product_idproduct = p.idproduct) as qty "
                + "from product p where p.stock_idstock='" + id + "'   ";
        try (
                ResultSet rs = DB.search(sql);) {
            DefaultTableModel dtm = (DefaultTableModel) tbl_stock.getModel();
            dtm.setRowCount(0);
            int count = 0;
            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("idproduct"));
                v.add(rs.getString("code"));
                v.add(rs.getString("name"));
                v.add(rs.getString("qty"));
                v.add(rs.getString("type"));
                dtm.addRow(v);
                count++;
            }
            if (count == 0) {
                JOptionPane.showMessageDialog(this, "No product found!");
            } else {
                JOptionPane.showMessageDialog(this, "Found " + count + " products!", null, JOptionPane.INFORMATION_MESSAGE);
                tf_id_stock.grabFocus();
                tf_id_stock.selectAll();

            }
        } catch (Exception e) {
            DB.processException(e);
        }
    }

    private void loadByStockName() {
        String name = tf_name_stock.getText();
        if (name.isEmpty()) {
            tf_name_stock.grabFocus();
            return;
        }

        String sql = "select *, (select coalesce(sum(qty),0) from sell_item where product_idproduct = p.idproduct) + "
                + "(select coalesce(sum(qty),0)  from raw_item where product_idproduct = p.idproduct) as qty "
                + "from product p where p.stock_idstock=(select idstock from stock where stockname='" + name + "')   ";
        try (
                ResultSet rs = DB.search(sql);) {
            DefaultTableModel dtm = (DefaultTableModel) tbl_stock.getModel();
            dtm.setRowCount(0);
            int count = 0;
            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("idproduct"));
                v.add(rs.getString("code"));
                v.add(rs.getString("name"));
                v.add(rs.getString("qty"));
                v.add(rs.getString("type"));
                dtm.addRow(v);
                count++;
            }
            if (count == 0) {
                JOptionPane.showMessageDialog(this, "No product found!");
            } else {
                JOptionPane.showMessageDialog(this, "Found " + count + " products!", null, JOptionPane.INFORMATION_MESSAGE);
                tf_name_stock.grabFocus();
                tf_name_stock.selectAll();
            }
        } catch (Exception e) {
            DB.processException(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    setDefaultLookAndFeelDecorated(true);
                    UIManager.setLookAndFeel(new SubstanceBusinessBlueSteelLookAndFeel());
                } catch (Exception e) {
                    e.printStackTrace();
                }
                new Stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lb_user;
    private javax.swing.JTable tbl_product;
    private javax.swing.JTable tbl_stock;
    private javax.swing.JTextField tf_id_product;
    private javax.swing.JTextField tf_id_stock;
    private javax.swing.JTextField tf_name_product;
    private javax.swing.JTextField tf_name_stock;
    // End of variables declaration//GEN-END:variables
}
